### ISSUE TITLE
The exception will cause the application to exit

### ISSUE THREAD

**Issue by xubinhua888** [easycaching-contrib/ec-freeredis#6]
CoreCLR Version: 6.0.1122.52304
.NET Version: 6.0.11
Description: The process was terminated due to an unhandled exception.
Exception Info: System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at EasyCaching.Bus.FreeRedis.DefaultFreeRedisBus.OnMessage(String topic, Object body)
   at FreeRedis.RedisClient.<>c__DisplayClass433_0.<Subscribe>b__0(String p, String k, Object d)
   at FreeRedis.RedisClient.PubSub.OnData(String pattern, Boolean ssub, String key, Object data)
   at FreeRedis.RedisClient.PubSub.<>c__DisplayClass18_0.<Subscribe>b__3()
   at System.Threading.Thread.StartHelper.Callback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Thread.StartCallback()

**Comment by Memoyu** [comment]
@xubinhua888  感谢您的反馈！
如果通过我们提供的pub方法进行消息推送应该不会有问题，
因为在pub时，我们内部会将消息进行封装，并且会进行base64处理，所以message格式应该为base64格式，sub才能正常解析。
